# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

jobs:
  include:
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8     # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install --upgrade pip 
  - pip3 install -r requirements.txt --use-mirrors

# Command to run tests, e.g. python setup.py test
script:

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: conolcedric
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: cedricconol/bertosaurus
#     python: 3.8
